### PR TITLE
Add in fru and DNE credentials objects

### PR DESCRIPTION
**Pull request by ekaley**

### CODE REVIEW

**Comment by giddyelysium** [comment]
@ekaley quick one for my understanding, what are all the credential objects for?

**Comment by ekaley** [comment]
@giddyelysium 

Ethan Kaley
[3:38 PM] 
so back to what i said before


[3:39] 
for 2/3 of the backend adapters we handle credentials one way (paqx sends uuid, adapter gets creds based on uuid) and for 1/3 of the adapters we handle creds another way (paqx sends nothing and adapter looks up sds, gets uuid then goes to creds with that uuid) (edited)


[3:40] 
@kushagra-mahajan ^?


Kushagra Mahajan 
[3:41 PM] 
yes that's what we don't like about rackhd adapter


[3:41] 
and the aggregators are tightly coupled with both the core services


Ethan Kaley
[3:41 PM] 
well we both dont like that about rhd adapter (edited)


Kushagra Mahajan 
[3:42 PM] 
??


Ethan Kaley
[3:42 PM] 
^^*


Kushagra Mahajan 
[3:42 PM] 
We don't like the aggregation, and giving so much of responsibilites to rackhd adapter


Ethan Kaley
[3:42 PM] 
anyway so... we are fixing the rackhd adapter and DNE paqx interaction with it? (edited)


Kushagra Mahajan 
[3:43 PM] 
:+1::skin-tone-3:


Ethan Kaley
[3:44 PM] 
because i believe our overlords @colmharrington and @paul endorse the `for 2/3 of the backend adapters we handle credentials one way (paqx sends uuid, adapter gets creds based on uuid)` way of doing things with sds and cred service?


[3:44] 
so it would make logical sense to make DNE paqx team do it that way^


Kushagra Mahajan 
[3:45 PM] 
the only issue if who will do that amount of refactoring? That's why I was not touching rackhd adapter and simply did that for the scaleio and vcenter. And if I would have followed the same approach as rackhd adapter, then we would have given too much responsibility to scaleio and vcenter adapter to find the correct components and its credentials


[3:46] 
which was wrong


[3:46] 
it would have been either 3/3 are wrong or 1/3 is wrong


Ethan Kaley
[3:47 PM] 
but it needs to be 3/3 RIGHT


[3:47] 
so the dne team refactors their code to be right


Kushagra Mahajan 
[3:47 PM] 
yes I totally agree


Ethan Kaley [3:47 PM] 
because thats the architecture


[3:47] 
however im not the one to mandate that.... so ill wait until paul or colm read this in the morning and chime in :slightly_smiling_face:


Kushagra Mahajan 
[3:48 PM] 
but its ok to add the creds obuject, just don't make that mandatory


[3:48] 
coz dne paqx won't be populating that object


Ethan Kaley
[3:49 PM] 
i can leave it mandatory and whenever the dne paqx fixes their code then ill merge it?


[3:49] 
becasue once they fix their code it'll now be "mandatory" lol


[3:51] 
im in no rush to merge that PR.... or any of the other changes were making to align/standardize the api's for fru and dne... just realizing that eventually it needs to be done but we can leave it 2/3 right and 1/3 wrong for however long @justink0 doesnt care about it lol

**Comment by giddyelysium** [comment]
@ekaley so when can we merge? :) :) Loving standardisation and improvement on contracts

**Comment by ekaley** [comment]
@giddyelysium ship this once it builds

**Pull request merged**
